services:
    beneficiary.household_service:
        class: BeneficiaryBundle\Utils\HouseholdService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@jms_serializer"
            - "@beneficiary.beneficiary_service"
            - "@request_validator"
            - "@location_service"
            - "@validator"
        public: true
    beneficiary.beneficiary_service:
        class: BeneficiaryBundle\Utils\BeneficiaryService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@jms_serializer"
            - "@request_validator"
            - "@validator"
        public: true
    beneficiary.country_specific_service:
        class: BeneficiaryBundle\Utils\CountrySpecificService
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

#####################################################################################################
####                                            CSV                                              ####
#####################################################################################################
    beneficiary.household_export_csv_service:
        class: BeneficiaryBundle\Utils\ExportCSVService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
        public: true
    beneficiary.household_csv_service:
        class: BeneficiaryBundle\Utils\HouseholdCSVService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@beneficiary.household_service"
            - "@beneficiary.beneficiary_service"
            - "@beneficiary.csv_to_array_mapper"
            - "@service_container"
        public: true
    beneficiary.csv_to_array_mapper:
        class: BeneficiaryBundle\Utils\Mapper\CSVToArrayMapper
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    beneficiary.household_to_csv_mapper:
        class: BeneficiaryBundle\Utils\Mapper\HouseholdToCSVMapper
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@jms_serializer"
        public: true