services:
    beneficiary.household_service:
        class: BeneficiaryBundle\Utils\HouseholdService
        arguments: ["@doctrine.orm.entity_manager", "@jms_serializer", "@beneficiary.beneficiary_service"]
        public: true
    beneficiary.beneficiary_service:
        class: BeneficiaryBundle\Utils\BeneficiaryService
        arguments: ["@doctrine.orm.entity_manager", "@jms_serializer"]
        public: true
    beneficiary.country_specific_service:
        class: BeneficiaryBundle\Utils\CountrySpecificService
        arguments: ["@doctrine.orm.entity_manager"]
        public: true