rest_user:
    type: rest
    resource: "@UserBundle/Resources/config/routing.yml"

rest_project:
    type: rest
    resource: "@ProjectBundle/Resources/config/routing.yml"

rest_beneficiary:
    type: rest
    resource: "@BeneficiaryBundle/Resources/config/routing.yml"
