# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        our_db_provider:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        # Config without security but only for profiler and images/scripts
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Config without security.
#        dev:
#            pattern:  ^/
#            security: false

        # tester
        tester_salt:
            pattern:   ^/api/wsse/salt
            security: false

        tester_login:
            pattern:   ^/api/wsse/login
            security: false

        wsse_secured:
            pattern:   ^/api/
            stateless: true
            wsse: true
            anonymous: false
            methods: [GET, PUT, POST, DELETE, OPTIONS]
            provider: our_db_provider

    access_control:
        - { path: /,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }


        # ADMIN PART
        - { path: ^/admin/,    role: ROLE_USER }
        - { path: ^/,          role: ROLE_USER }

    role_hierarchy:
        ROLE_REPORTING:               [ROLE_REPORTING_READ, ROLE_REPORTING_WRITE]
        ROLE_PROJECT_MANAGEMENT:      [ROLE_PROJECT_MANAGEMENT_READ, ROLE_PROJECT_MANAGEMENT_WRITE]
        ROLE_BENEFICIARY_MANAGEMENT:  [ROLE_BENEFICIARY_MANAGEMENT_READ, ROLE_BENEFICIARY_MANAGEMENT_WRITE]
        ROLE_USER_MANAGEMENT:         [ROLE_USER_MANAGEMENT_READ, ROLE_USER_MANAGEMENT_WRITE]
        ROLE_BENEFICIARY_INFORMATION: [ROLE_BENEFICIARY_INFORMATION_READ]
        ROLE_AUTHORISE_PAYMENT:       [ROLE_AUTHORISE_PAYMENT]

        ROLE_READ_ONLY:               [ROLE_REPORTING_READ, ROLE_BENEFICIARY_INFORMATION_READ]
        ROLE_FIELD_OFFICER:           [ROLE_PROJECT_MANAGEMENT_READ, ROLE_REPORTING_READ, ROLE_BENEFICIARY_MANAGEMENT]
        ROLE_PROJECT_OFFICER:         [ROLE_PROJECT_MANAGEMENT_READ, ROLE_REPORTING, ROLE_BENEFICIARY_MANAGEMENT]
        ROLE_PROJECT_MANAGER:         [ROLE_PROJECT_MANAGEMENT, ROLE_REPORTING, ROLE_BENEFICIARY_MANAGEMENT, ROLE_AUTHORISE_PAYMENT]
        ROLE_COUNTRY_MANAGER:         [ROLE_USER_MANAGEMENT, ROLE_PROJECT_MANAGEMENT, ROLE_BENEFICIARY_MANAGEMENT, ROLE_REPORTING, ROLE_AUTHORISE_PAYMENT]
        ROLE_REGIONAL_MANAGER:        [ROLE_PROJECT_MANAGEMENT_READ, ROLE_REPORTING_READ, ROLE_BENEFICIARY_MANAGEMENT_READ, ROLE_AUTHORISE_PAYMENT]
