services:
    CommonBundle\Listener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    ##########################################################################
    ####                           DATAFIXTURES                           ####
    ##########################################################################
    CommonBundle\DataFixtures\VulnerabilityCriterionFixtures:
        tags:
            - { name: doctrine.fixture.orm }
    CommonBundle\DataFixtures\CountrySpecificFixtures:
        tags:
            - { name: doctrine.fixture.orm }
    CommonBundle\DataFixtures\ProjectFixtures:
        tags:
            - { name: doctrine.fixture.orm }
    CommonBundle\DataFixtures\SectorFixtures:
        tags:
            - { name: doctrine.fixture.orm }


    ##########################################################################
    ####                              VOTERS                              ####
    ##########################################################################

    voter_default:
        class: CommonBundle\Voter\DefaultVoter
        arguments: ["@security.role_hierarchy", "@doctrine.orm.entity_manager", "@request_stack"]
        tags:
            - { name: security.voter }