services:
    CommonBundle\Listener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

#    DataFixtures
    CommonBundle\DataFixtures\VulnerabilityCriterionFixtures:
        tags:
            - { name: doctrine.fixture.orm }
    CommonBundle\DataFixtures\CountrySpecificFixtures:
        tags:
            - { name: doctrine.fixture.orm }