services:
    distribution.distribution_service:
        class: DistributionBundle\Utils\DistributionService
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer', '@validator', '@location_service']
        public: true

    distribution.distribution_beneficiary_service:
        class: DistributionBundle\Utils\DistributionBeneficiaryService
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer', '@validator']

    location_service:
        class: DistributionBundle\Utils\LocationService
        arguments: ['@doctrine.orm.entity_manager', "@request_validator"]
        public: true
        public: true

    distribution.criteria_distribution_service:
        class: DistributionBundle\Utils\CriteriaDistributionService
        arguments: ['@doctrine.orm.entity_manager', '@distribution.configuration_loader']
        public: true

    distribution.configuration_loader:
        class: DistributionBundle\Utils\ConfigurationLoader
        arguments: ['@doctrine.orm.entity_manager', '%distribution.criteria%']
        public: true
