services:
    distribution.distribution_service:
        class: DistributionBundle\Utils\DistributionService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@jms_serializer'
            - '@validator'
            - '@location_service'
            - '@distribution.commodity_service'
            - '@distribution.configuration_loader'

    distribution.distribution_beneficiary_service:
        class: DistributionBundle\Utils\DistributionBeneficiaryService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@jms_serializer'
            - '@validator'

    location_service:
        class: DistributionBundle\Utils\LocationService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@request_validator"

    distribution.criteria_distribution_service:
        class: DistributionBundle\Utils\CriteriaDistributionService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@distribution.configuration_loader'

    distribution.configuration_loader:
        class: DistributionBundle\Utils\ConfigurationLoader
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%distribution.criteria%'

    distribution.modality_service:
        class: DistributionBundle\Utils\ModalityService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    distribution.commodity_service:
        class: DistributionBundle\Utils\CommodityService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
