services:
    project.project_service:
        class: ProjectBundle\Utils\ProjectService
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer', '@debug.validator']
        public: true
    project.donor_service:
        class: ProjectBundle\Utils\DonorService
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer', '@debug.validator']
        public: true
