---

- name: Create build directory
  file:
    path: '{{ workspace }}/build'
    state: directory

- name: Create k8s files
  template:
    src: '{{ item }}.j2'
    dest: '{{ workspace }}/build/{{ item }}'
  with_items:
    - persistentvolume.yaml
    - nginx-config.yaml
    - parameter-config.yaml
    - k8s-hummansis-db.yaml
    - k8s-hummansis-deploy.yaml

- name: Apply deployment
  shell: 'kubectl apply -f {{ workspace }}/build/{{ item }}'
  with_items:
    - persistentvolume.yaml
    - nginx-config.yaml
    - parameter-config.yaml
    - k8s-hummansis-db.yaml
    - k8s-hummansis-deploy.yaml
  when: lookup('env', 'JENKINS_HOME')
